package com.valhalla

const val OKHTTP_CONNECT_TIMEOUT_SECONDS = 15L
const val OKHTTP_READ_TIMEOUT_SECONDS = 15L
const val OKHTTP_WRITE_TIMEOUT_SECONDS = 15L

const val CACHE_SIZE = (10L * 1024L * 1024L) // 10MB
